language: c++
os: osx

matrix:
  include:
    - osx_image: xcode10.2
    - osx_image: xcode10.1
    - osx_image: xcode10
    - osx_image: xcode9.4
    - osx_image: xcode9.3
    - osx_image: xcode9.2
    - osx_image: xcode9.1
    - osx_image: xcode9
    - osx_image: xcode8.3
    - osx_image: xcode8
    - osx_image: xcode7.3
    - osx_image: xcode6.4

script:
  - clang++ --version
  - clang++ unique_ptr.cpp -stdlib=libc++ --target=x86_64-apple-darwin
